# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9fe64ee6987e459138dce993e6cac283fe87922ddbdf6ae81219ca5a02ecac37559c461e609057efb7e6aec287de5bf63e79dc0b1bb18485be8adf6aba96dad1

test:
  secret_key_base: e539059c6aa2135cfe8e157fff51c3ca0ad71e5c8d8d38bc63106f8503e7cf37cc08719984053eab53fc47757f63a0fe712e5df9f2c5a9da0df9aebbff513860

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
